CREATE OR REPLACE MODEL Maketnida.sample_4_1_C

OPTIONS(model_type='kmeans'
     , num_clusters =4 
     , kmeans_init_method = 'kmeans++'
     , max_iterations=30 )

AS (
 SELECT 
        COUNT(DISTINCT BASKET_ID) AS TOTAL_VISIT
    ,   SUM(SPEND) AS TOTAL_SPEND
    ,   SUM(SPEND)/COUNT(DISTINCT SHOP_DATE) AS AVG_DATE_SPEND
    ,   SUM(SPEND)/COUNT(DISTINCT SHOP_WEEK) AS AVG_WEEK_SPEND
    ,   SUM(SPEND)/COUNT(DISTINCT SHOP_WEEKDAY) AS AVG_WEEKDAY_SPEND
    ,   SUM(SPEND)/COUNT(DISTINCT BASKET_ID) AS TICKET_SIZE
    ,   SUM(SPEND)/COUNT(DISTINCT CUST_CODE) AS AVG_CUST_SPEND
FROM `silent-vim-308203.Maketnida.maketnida` 
WHERE CUST_CODE IS NOT NULL
GROUP BY CUST_CODE
 )
